### ISSUE TITLE
Extension does not work with Queue Panel extension.

### ISSUE THREAD

**Issue by Blurvy** [Resxt/Spicetify-Extensions#4]
I love this extension but I am unfortunately I am unable to use it with kyrie25's Queue Panel. This is the extension I'm talking about: https://github.com/kyrie25/spicetify-queue-panel.

**Comment by Resxt** [comment]
This repository is a collection of all of my extensions so which one are you talking about?

**Comment by Blurvy** [comment]
Sorry about that, I am talking about your full queue clear extensions.

**Comment by Resxt** [comment]
By taking a quick look at it, it seems like this extension replaces the queue button with its own meaning my extension tries to add its listeners/logic to a button that doesn't exist anymore.

Seems like I'm the one who has to adapt his code for when people use both extensions.
I'll try to work on it when I have some time and I'll get back to you when I have some info or if I update the extension
